[package]
name = "neuron-cli"
version = "0.1.0"
authors = ["GetPsyched"]
edition = "2021"
description = "CLI for neuron"

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
neuron = { path = "../neuron" }
